version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: school-platform-db
    environment:
      POSTGRES_DB: school_platform
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d school_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: